name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install doxygen
      run:  sudo apt-get install doxygen
    
    - name: Documentation
      run:  make doc -C Project/3_Implementation
    
